import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });
import InstagramLogo from "../public/instagram-logo.png";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image
          src={InstagramLogo}
          alt="Instagram Logo"
          width={120}
          height={24}
          className="pt-4 pl-4"
        />
        {children}
      </body>
    </html>
  );
}
